### ISSUE TITLE
What about common provider for a few nodes?

### ISSUE THREAD

**Issue by korjavin** [lucasepe/draft#1]
I'd like to group objects in one k8s cluster.

**Comment by lucasepe** [comment]
Yes just yesterday I was thinking of a "Group" entity...something like this:

```yaml
groups:
  - 
    label: AWS
    fillColor: '#cccccc'
    lineColor: '.....'
    components:
    - gt1 # or your 'api-gateway' component ID
    - ms2 # or your 'microservice' component ID 
```

...or making the 'provider' work as a 'grouper' adding a new 'impl' attribute to eventually specify the technology used. 

Example:

```yaml
--- 
components: 
  - 
    kind: function
    label: "Create\nAuth Challange"
    provider: AWS  # <- this will define the group
    impl: Lambda   # <- this will define the implementation
```

I like the latter more.
