### ISSUE TITLE
Another field for service: contact

### ISSUE THREAD

**Issue by korjavin** [lucasepe/draft#2]
What about another field for service: contact?

Adding everything with label: " ... \n ..."  not that convenient.

**Comment by lucasepe** [comment]
can you elaborate more? maybe with some example?

**Comment by korjavin** [comment]
Yeah, I have a need to add "contact email" to every microservice. Like a person who is responsible for it or like that.

The only way I can make it now is: it's use label:"blabla \n contact \n "

Hard to force to fill that.

**Comment by lucasepe** [comment]
You can use a YAML Literal Block Scalar [https://yaml-multiline.info/](https://yaml-multiline.info/) something like this:

```yaml
--- 
components: 
  - 
    kind: service
    label: |
      μService A
      contact: pippo@email.it
```

then running as usual: 

```bash
draft test.yml | dot -Tpng > test.png
```
result in:

![contact](https://user-images.githubusercontent.com/585381/84146381-eb05e780-aa5b-11ea-81c7-d70a3c5fac53.png)
